ducklake_vaccinations:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: duck_lakehouse/ducklake/catalog/dbt_local.duckdb
      extensions:
        - ducklake
      attach:
        - path: "ducklake:duck_lakehouse/ducklake/catalog/vaccination_lake.ducklake"
          alias: vaccination_lake
          options:
            data_path: "duck_lakehouse/ducklake/data"
            override_data_path: true
    prod:
      type: duckdb
      path: /app/data/catalog/dbt_local.duckdb
      extensions:
        - ducklake
      attach:
        - path: "ducklake:/app/data/catalog/vaccination_lake.ducklake"
          alias: vaccination_lake
          options:
            data_path: "/app/data/parquet"
            override_data_path: true